### PR TITLE
Fix decoration of listener when StatsD is enabled (fixes #138)

### LINKED ISSUE #138: StatsD timer decorator crashes with functools.partial
When statsd is enabled:

```
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/bin/kinto", line 11, in <module>
    load_entry_point('kinto', 'console_scripts', 'kinto')()
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/lib/python2.7/site-packages/kinto-4.1.1-py2.7.egg/kinto/__main__.py", line 149, in main
    pserve.main(pserve_argv)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 60, in main
    return command.run()
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 371, in run
    global_conf=vars)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 406, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/lib/python2.7/site-packages/kinto-4.1.1-py2.7.egg/kinto/__init__.py", line 51, in main
    default_settings=DEFAULT_SETTINGS)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/lib/python2.7/site-packages/kinto-4.1.1-py2.7.egg/kinto/core/initialization.py", line 579, in initialize
    config.include("kinto.core", route_prefix=api_version)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/lib/python2.7/site-packages/kinto-4.1.1-py2.7.egg/kinto/core/__init__.py", line 166, in includeme
    config.include(app)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/home/mathieu/Code/Mozilla/kinto-signer/kinto_signer/__init__.py", line 114, in includeme
    sign_data_listener = statsd_client.timer(key)(sign_data_listener)
  File "build/bdist.linux-x86_64/egg/statsd/client.py", line 26, in __call__
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

Introduced with #125

### PR DESCRIPTION
**Pull request by leplatrem**
@Natim r?

### CODE REVIEW

**Comment by Natim** [comment]
Can we add a test for this?

File: kinto_signer/__init__.py [hunk 1]
```diff
@@ -107,8 +107,14 @@ def includeme(config):
 
     sign_data_listener = functools.partial(listeners.sign_collection_data,
                                            resources=resources)
+
     # If StatsD is enabled, monitor execution time of listener.
     if config.registry.statsd:
+        # Due to https://github.com/jsocol/pystatsd/issues/85
+        for attr in ('__module__', '__name__'):
```
Comment (Natim) [inline kinto_signer/__init__.py]: Should we use @wraps?

Comment (leplatrem) [inline kinto_signer/__init__.py]: The problem comes from `functools.wrap` actually...
